### ISSUE TITLE
Uncaught TypeError: a.destroy is not a function when image upload failed in editor

### ISSUE THREAD

**Issue by sdelcroix** [decidim-ice/decidim-module-decidim_awesome#262]
**Describe the bug**
When a error occurs during image upload in text editor (for example by using an image with a width greater than 3840 pixels), there's an error message that appears under the text field then fade.
The HTML element of this message is then intended to be removed from DOM, but the jQuery method used on this element is "destroy()".
This method doesn't exist in jQuery thus a javascript error occurs : Uncaught TypeError: a.destroy is not a function

"destroy()" has to be replaced by "remove()" : https://api.jquery.com/remove/#remove-selector

**Desktop (please complete the following information):**
 - OS: macOS 12.7.2
 - Browser : Chrome
 - Version 120

**Additional context**
Here the browser Javascript trace :
```
Uncaught TypeError: a.destroy is not a function
    at HTMLParagraphElement.<anonymous> (editor.js:116:16)
    at r.complete (jquery.js:7736:12)
    at u (jquery.js:3500:31)
    at Object.fireWith [as resolveWith] (jquery.js:3630:7)
    at u (jquery.js:7579:13)
    at E.fx.tick (jquery.js:7903:19)
    at ut (jquery.js:7282:13)
```

**Comment by sdelcroix** [comment]
I confirm this issue is fixed in Awesome 0.9.x and Decidim 0.27
