### ISSUE TITLE
Error compiling assets with Decidim 0.26.9 and Decidim Awesome 0.10.2

### ISSUE THREAD

**Issue by maintainer-partecipa** [decidim-ice/decidim-module-decidim_awesome#287]
**Describe the bug**
When I try to compile assets with Webpacker on Decidim version 0.26.9 and Decidim Awesome version 0.10,2, I obtain an error on the CSS of Decidim Awesome

ERROR in css/decidim_decidim_awesome-1a030200.css from Css Minimizer
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: $rectangle-width * 2
^..^
    at /home/decidim/.../css/decidim_decidim_awesome-1a030200.css:119:15990
    at Object.parseError (/home/decidim/.../node_modules/postcss-calc/dist/parser.js:1200:15)
    at Object.lexer_parseError [as parseError] (/home/decidim/.../node_modules/postcss-calc/dist/parser.js:2333:44)
    at Object.lexer_next [as next] (/home/decidim/.../node_modules/postcss-calc/dist/parser.js:3328:22)
    at Object.lexer_fastLex [as fastLex] (/home/decidim/.../node_modules/postcss-calc/dist/parser.js:3403:18)
    at fastLex (/home/decidim/.../node_modules/postcss-calc/dist/parser.js:1603:27)
    at Parser.parse (/home/decidim/.../node_modules/postcss-calc/dist/parser.js:1677:30)
    at /home/decidim/.../node_modules/postcss-calc/dist/lib/transform.js:33:30
    at walk (/home/decidim/.../node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (/home/decidim/.../node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/home/decidim/.../node_modules/postcss-calc/dist/lib/transform.js:24:50)

**To Reproduce**
Install Decidim version 0.26.9 and Decidim Awesome version 0.10,2
Install Webpacker
Compile assets with Webpacker

**Expected behavior**
Assets should be compiled by webpacker

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Whatever
 - Version: 0.10.2 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maintainer-partecipa** [comment]
I've solved the problem, for whoever should find a similar error this is how I solved. 
I've deleted the node_modules folder and the public/decidim-packs folder, then I deleted the package-lock.json (or save it with another name). Then reinstalled the node packages with "npm i" (in my case yarn returns an error) . Then I've added the decidim awesome assets and in the end webpacker had compiled.
